esphome:
  name: esp-regenput

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

api:
# enc NOT in openhab...
#  encryption:
#   key: !secret api_encryption_key

i2c:
  scl: D2
  sda: D3
  scan: true
  frequency: 10

ads1115:
  - address: 0x48

sensor:
  - platform: adc
    id: regenput_waterstand
    pin: A0
    name: "Regenput waterstand oud"
    update_interval: 300s
    unit_of_measurement: "mm"
    accuracy_decimals: 0
    filters:
    - multiply: 3.3   # compensate internal divider on the board
    - lambda: return (187.5*(x/0.150-4.0))/1;   # conversion Volt to mm
  - platform: ads1115
    multiplexer: 'A0_GND'
    name: "Regenput waterstand"
    gain: 4.096
    accuracy_decimals: 0
    update_interval: 300s
    unit_of_measurement: "mm"
    filters:
    - lambda: return (187.5*(x/0.150-4.0))/1;   # conversion Volt to mm

web_server:
  port: 8080


