esphome:
  name: esp-regenput

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome
  password: !secret ota_password

api:
# enc NOT in openhab...
#  encryption:
#   key: !secret api_encryption_key

i2c:
  scl: D2
  sda: D3
  scan: true
  frequency: 10

ads1115:
  - address: 0x48

sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    name: "Regenput ADC spanning"
    id: adc_output
    update_interval: 300s
    gain: 4.096
    unit_of_measurement: "V"
    accuracy_decimals: 6
  - platform: copy
    source_id: adc_output
    name: "Regenput waterstand"
    unit_of_measurement: "mm"
    filters:
    - lambda: return 12.5*(100.0*x - 60.0);   # conversion Volt to mm
    - round: 0
    accuracy_decimals: 0

web_server:
  port: 8080


