esphome:
  name: esp-regenput

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: !secret ota_password

api:
# enc NOT in openhab...
#  encryption:
#    key: !secret api_encryption_key


sensor:
  - platform: adc
    id: regenput_waterstand
    pin: A0
    name: "Regenput waterstand"
    update_interval: 300s
    unit_of_measurement: "mm"
    accuracy_decimals: 0
    filters: 
      - multiply: 3.3   # compensate internal divider on the board
      - lambda: return (187.5*(x/0.150-4.0))/1;   # conversion Volt to mm

#web_server:
#  port: 8080



