# Basic Config
esphome:
  name: sonoff-s20-1
  
esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: !secret ota_password

api:
# enc NOT in openhab...
#  encryption:
#    key: !secret api_encryption_key

output:
  - id: green_led_out
    platform: gpio
    pin:
      number: GPIO13
      inverted: true
  - id: relay_out
    platform: gpio
    pin: GPIO12

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S20 Button"
    on_press:
      then:
      - switch.toggle: relay_sw

switch:
  - platform: output
    name: "Sonoff S20 Relay"
    id: relay_sw
    output: relay_out

light:
  - platform: binary
    name: "Sonoff S20 Green LED"
    output: green_led_out
