### warning: this esphome yaml uses variable $hostname, and depends on secrets.yaml

esphome:
  name: $hostname

esp8266:
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret wifi1_ssid
    password: !secret wifi1_password
  - ssid: !secret wifi2_ssid
    password: !secret wifi2_password

ota:
  - platform: esphome
    password: !secret ota_password

api:
# enc NOT in openhab...
#  encryption:
#    key: !secret api_encryption_key


output:
  - id: blue_led
    platform: gpio
    pin:
      number: GPIO13
      inverted: true
  - id: relay_out
    platform: gpio
    pin: GPIO12


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Sonoff S26 Button"
    on_press:
      then:
      - switch.toggle: relay_sw

switch:
  - platform: output
    name: "Sonoff S26 Relay"
    id: relay_sw
    output: relay_out

light:
  - platform: binary
    name: "Sonoff S26 Blue LED"
    output: blue_led


